// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: document.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentType int32

const (
	DocumentType_DOC_TYPE_UNSPECIFIED DocumentType = 0
	DocumentType_DOC_TYPE_XML         DocumentType = 1
	DocumentType_DOC_TYPE_PDF         DocumentType = 2
	DocumentType_DOC_TYPE_JSON        DocumentType = 3
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "DOC_TYPE_UNSPECIFIED",
		1: "DOC_TYPE_XML",
		2: "DOC_TYPE_PDF",
		3: "DOC_TYPE_JSON",
	}
	DocumentType_value = map[string]int32{
		"DOC_TYPE_UNSPECIFIED": 0,
		"DOC_TYPE_XML":         1,
		"DOC_TYPE_PDF":         2,
		"DOC_TYPE_JSON":        3,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

type DocumentStatus int32

const (
	DocumentStatus_DOC_STATUS_UNSPECIFIED DocumentStatus = 0
	DocumentStatus_DOC_STATUS_PENDING     DocumentStatus = 1
	DocumentStatus_DOC_STATUS_RECEIVED    DocumentStatus = 2
	DocumentStatus_DOC_STATUS_PROCESSED   DocumentStatus = 3
	DocumentStatus_DOC_STATUS_FAILED      DocumentStatus = 4
	DocumentStatus_DOC_STATUS_SUCCESSFUL  DocumentStatus = 5
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "DOC_STATUS_UNSPECIFIED",
		1: "DOC_STATUS_PENDING",
		2: "DOC_STATUS_RECEIVED",
		3: "DOC_STATUS_PROCESSED",
		4: "DOC_STATUS_FAILED",
		5: "DOC_STATUS_SUCCESSFUL",
	}
	DocumentStatus_value = map[string]int32{
		"DOC_STATUS_UNSPECIFIED": 0,
		"DOC_STATUS_PENDING":     1,
		"DOC_STATUS_RECEIVED":    2,
		"DOC_STATUS_PROCESSED":   3,
		"DOC_STATUS_FAILED":      4,
		"DOC_STATUS_SUCCESSFUL":  5,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_document_proto_enumTypes[1].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_document_proto_enumTypes[1]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Type          DocumentType           `protobuf:"varint,2,opt,name=type,proto3,enum=go_edi_document_processor.DocumentType" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SenderId      string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=go_edi_document_processor.DocumentStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Document) GetType() DocumentType {
	if x != nil {
		return x.Type
	}
	return DocumentType_DOC_TYPE_UNSPECIFIED
}

func (x *Document) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Document) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Document) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Document) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOC_STATUS_UNSPECIFIED
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SendDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentRequest) Reset() {
	*x = SendDocumentRequest{}
	mi := &file_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentRequest) ProtoMessage() {}

func (x *SendDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentRequest.ProtoReflect.Descriptor instead.
func (*SendDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{1}
}

func (x *SendDocumentRequest) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type SendDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=go_edi_document_processor.DocumentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentResponse) Reset() {
	*x = SendDocumentResponse{}
	mi := &file_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentResponse) ProtoMessage() {}

func (x *SendDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentResponse.ProtoReflect.Descriptor instead.
func (*SendDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{2}
}

func (x *SendDocumentResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SendDocumentResponse) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOC_STATUS_UNSPECIFIED
}

type GetDocumentByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentByUUIDRequest) Reset() {
	*x = GetDocumentByUUIDRequest{}
	mi := &file_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentByUUIDRequest) ProtoMessage() {}

func (x *GetDocumentByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetDocumentByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentByUUIDResponse) Reset() {
	*x = GetDocumentByUUIDResponse{}
	mi := &file_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentByUUIDResponse) ProtoMessage() {}

func (x *GetDocumentByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{4}
}

func (x *GetDocumentByUUIDResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

type ReceiveDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveDocumentRequest) Reset() {
	*x = ReceiveDocumentRequest{}
	mi := &file_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveDocumentRequest) ProtoMessage() {}

func (x *ReceiveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveDocumentRequest.ProtoReflect.Descriptor instead.
func (*ReceiveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{5}
}

type ReceiveDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveDocumentResponse) Reset() {
	*x = ReceiveDocumentResponse{}
	mi := &file_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveDocumentResponse) ProtoMessage() {}

func (x *ReceiveDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveDocumentResponse.ProtoReflect.Descriptor instead.
func (*ReceiveDocumentResponse) Descriptor() ([]byte, []int) {
	return file_document_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_document_proto protoreflect.FileDescriptor

const file_document_proto_rawDesc = "" +
	"\n" +
	"\x0edocument.proto\x12\x19go_edi_document_processor\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x0evalidate.proto\"\x83\x03\n" +
	"\bDocument\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12E\n" +
	"\x04type\x18\x02 \x01(\x0e2'.go_edi_document_processor.DocumentTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12)\n" +
	"\vreceiver_id\x18\x05 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\n" +
	"receiverId\x12A\n" +
	"\x06status\x18\a \x01(\x0e2).go_edi_document_processor.DocumentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"`\n" +
	"\x13SendDocumentRequest\x12I\n" +
	"\bdocument\x18\x01 \x01(\v2#.go_edi_document_processor.DocumentB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bdocument\"p\n" +
	"\x14SendDocumentResponse\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12A\n" +
	"\x06status\x18\x02 \x01(\x0e2).go_edi_document_processor.DocumentStatusR\x06status\"8\n" +
	"\x18GetDocumentByUUIDRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x04uuid\"\\\n" +
	"\x19GetDocumentByUUIDResponse\x12?\n" +
	"\bdocument\x18\x01 \x01(\v2#.go_edi_document_processor.DocumentR\bdocument\"\x18\n" +
	"\x16ReceiveDocumentRequest\"Z\n" +
	"\x17ReceiveDocumentResponse\x12?\n" +
	"\bdocument\x18\x01 \x01(\v2#.go_edi_document_processor.DocumentR\bdocument*_\n" +
	"\fDocumentType\x12\x18\n" +
	"\x14DOC_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDOC_TYPE_XML\x10\x01\x12\x10\n" +
	"\fDOC_TYPE_PDF\x10\x02\x12\x11\n" +
	"\rDOC_TYPE_JSON\x10\x03*\xa9\x01\n" +
	"\x0eDocumentStatus\x12\x1a\n" +
	"\x16DOC_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DOC_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13DOC_STATUS_RECEIVED\x10\x02\x12\x18\n" +
	"\x14DOC_STATUS_PROCESSED\x10\x03\x12\x15\n" +
	"\x11DOC_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15DOC_STATUS_SUCCESSFUL\x10\x052\xd5\x03\n" +
	"\x0fDocumentService\x12\x8c\x01\n" +
	"\fSendDocument\x12..go_edi_document_processor.SendDocumentRequest\x1a/.go_edi_document_processor.SendDocumentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/doc/send\x12\x9a\x01\n" +
	"\x11GetDocumentByUUID\x123.go_edi_document_processor.GetDocumentByUUIDRequest\x1a4.go_edi_document_processor.GetDocumentByUUIDResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/doc/{uuid}\x12\x95\x01\n" +
	"\x0fReceiveDocument\x121.go_edi_document_processor.ReceiveDocumentRequest\x1a2.go_edi_document_processor.ReceiveDocumentResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/doc/receiveB6Z4github.com/go-edi-document-processor/api/proto;protob\x06proto3"

var (
	file_document_proto_rawDescOnce sync.Once
	file_document_proto_rawDescData []byte
)

func file_document_proto_rawDescGZIP() []byte {
	file_document_proto_rawDescOnce.Do(func() {
		file_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)))
	})
	return file_document_proto_rawDescData
}

var file_document_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_document_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_document_proto_goTypes = []any{
	(DocumentType)(0),                 // 0: go_edi_document_processor.DocumentType
	(DocumentStatus)(0),               // 1: go_edi_document_processor.DocumentStatus
	(*Document)(nil),                  // 2: go_edi_document_processor.Document
	(*SendDocumentRequest)(nil),       // 3: go_edi_document_processor.SendDocumentRequest
	(*SendDocumentResponse)(nil),      // 4: go_edi_document_processor.SendDocumentResponse
	(*GetDocumentByUUIDRequest)(nil),  // 5: go_edi_document_processor.GetDocumentByUUIDRequest
	(*GetDocumentByUUIDResponse)(nil), // 6: go_edi_document_processor.GetDocumentByUUIDResponse
	(*ReceiveDocumentRequest)(nil),    // 7: go_edi_document_processor.ReceiveDocumentRequest
	(*ReceiveDocumentResponse)(nil),   // 8: go_edi_document_processor.ReceiveDocumentResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_document_proto_depIdxs = []int32{
	0,  // 0: go_edi_document_processor.Document.type:type_name -> go_edi_document_processor.DocumentType
	1,  // 1: go_edi_document_processor.Document.status:type_name -> go_edi_document_processor.DocumentStatus
	9,  // 2: go_edi_document_processor.Document.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: go_edi_document_processor.Document.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: go_edi_document_processor.SendDocumentRequest.document:type_name -> go_edi_document_processor.Document
	1,  // 5: go_edi_document_processor.SendDocumentResponse.status:type_name -> go_edi_document_processor.DocumentStatus
	2,  // 6: go_edi_document_processor.GetDocumentByUUIDResponse.document:type_name -> go_edi_document_processor.Document
	2,  // 7: go_edi_document_processor.ReceiveDocumentResponse.document:type_name -> go_edi_document_processor.Document
	3,  // 8: go_edi_document_processor.DocumentService.SendDocument:input_type -> go_edi_document_processor.SendDocumentRequest
	5,  // 9: go_edi_document_processor.DocumentService.GetDocumentByUUID:input_type -> go_edi_document_processor.GetDocumentByUUIDRequest
	7,  // 10: go_edi_document_processor.DocumentService.ReceiveDocument:input_type -> go_edi_document_processor.ReceiveDocumentRequest
	4,  // 11: go_edi_document_processor.DocumentService.SendDocument:output_type -> go_edi_document_processor.SendDocumentResponse
	6,  // 12: go_edi_document_processor.DocumentService.GetDocumentByUUID:output_type -> go_edi_document_processor.GetDocumentByUUIDResponse
	8,  // 13: go_edi_document_processor.DocumentService.ReceiveDocument:output_type -> go_edi_document_processor.ReceiveDocumentResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_document_proto_init() }
func file_document_proto_init() {
	if File_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_document_proto_rawDesc), len(file_document_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_document_proto_goTypes,
		DependencyIndexes: file_document_proto_depIdxs,
		EnumInfos:         file_document_proto_enumTypes,
		MessageInfos:      file_document_proto_msgTypes,
	}.Build()
	File_document_proto = out.File
	file_document_proto_goTypes = nil
	file_document_proto_depIdxs = nil
}
