// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: document.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _document_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Document with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Document) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Document with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DocumentMultiError, or nil
// if none found.
func (m *Document) ValidateAll() error {
	return m.validate(true)
}

func (m *Document) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocId

	if _, ok := DocumentType_name[int32(m.GetType())]; !ok {
		err := DocumentValidationError{
			field:  "Type",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Content

	// no validation rules for SenderId

	if err := m._validateUuid(m.GetReceiverId()); err != nil {
		err = DocumentValidationError{
			field:  "ReceiverId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DocumentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DocumentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DocumentValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DocumentMultiError(errors)
	}

	return nil
}

func (m *Document) _validateUuid(uuid string) error {
	if matched := _document_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DocumentMultiError is an error wrapping multiple validation errors returned
// by Document.ValidateAll() if the designated constraints aren't met.
type DocumentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DocumentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DocumentMultiError) AllErrors() []error { return m }

// DocumentValidationError is the validation error returned by
// Document.Validate if the designated constraints aren't met.
type DocumentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DocumentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DocumentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DocumentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DocumentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DocumentValidationError) ErrorName() string { return "DocumentValidationError" }

// Error satisfies the builtin error interface
func (e DocumentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDocument.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DocumentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DocumentValidationError{}

// Validate checks the field values on SendDocumentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendDocumentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendDocumentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendDocumentRequestMultiError, or nil if none found.
func (m *SendDocumentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendDocumentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetDocument() == nil {
		err := SendDocumentRequestValidationError{
			field:  "Document",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetDocument()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SendDocumentRequestValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SendDocumentRequestValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDocument()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SendDocumentRequestValidationError{
				field:  "Document",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SendDocumentRequestMultiError(errors)
	}

	return nil
}

// SendDocumentRequestMultiError is an error wrapping multiple validation
// errors returned by SendDocumentRequest.ValidateAll() if the designated
// constraints aren't met.
type SendDocumentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendDocumentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendDocumentRequestMultiError) AllErrors() []error { return m }

// SendDocumentRequestValidationError is the validation error returned by
// SendDocumentRequest.Validate if the designated constraints aren't met.
type SendDocumentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendDocumentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendDocumentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendDocumentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendDocumentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendDocumentRequestValidationError) ErrorName() string {
	return "SendDocumentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendDocumentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendDocumentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendDocumentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendDocumentRequestValidationError{}

// Validate checks the field values on SendDocumentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendDocumentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendDocumentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendDocumentResponseMultiError, or nil if none found.
func (m *SendDocumentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SendDocumentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DocId

	// no validation rules for Status

	if len(errors) > 0 {
		return SendDocumentResponseMultiError(errors)
	}

	return nil
}

// SendDocumentResponseMultiError is an error wrapping multiple validation
// errors returned by SendDocumentResponse.ValidateAll() if the designated
// constraints aren't met.
type SendDocumentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendDocumentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendDocumentResponseMultiError) AllErrors() []error { return m }

// SendDocumentResponseValidationError is the validation error returned by
// SendDocumentResponse.Validate if the designated constraints aren't met.
type SendDocumentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendDocumentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendDocumentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendDocumentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendDocumentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendDocumentResponseValidationError) ErrorName() string {
	return "SendDocumentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SendDocumentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendDocumentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendDocumentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendDocumentResponseValidationError{}

// Validate checks the field values on GetDocumentByUUIDRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDocumentByUUIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDocumentByUUIDRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDocumentByUUIDRequestMultiError, or nil if none found.
func (m *GetDocumentByUUIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDocumentByUUIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUuid()); err != nil {
		err = GetDocumentByUUIDRequestValidationError{
			field:  "Uuid",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetDocumentByUUIDRequestMultiError(errors)
	}

	return nil
}

func (m *GetDocumentByUUIDRequest) _validateUuid(uuid string) error {
	if matched := _document_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetDocumentByUUIDRequestMultiError is an error wrapping multiple validation
// errors returned by GetDocumentByUUIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDocumentByUUIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDocumentByUUIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDocumentByUUIDRequestMultiError) AllErrors() []error { return m }

// GetDocumentByUUIDRequestValidationError is the validation error returned by
// GetDocumentByUUIDRequest.Validate if the designated constraints aren't met.
type GetDocumentByUUIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDocumentByUUIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDocumentByUUIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDocumentByUUIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDocumentByUUIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDocumentByUUIDRequestValidationError) ErrorName() string {
	return "GetDocumentByUUIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDocumentByUUIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDocumentByUUIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDocumentByUUIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDocumentByUUIDRequestValidationError{}

// Validate checks the field values on GetDocumentByUUIDResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDocumentByUUIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDocumentByUUIDResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDocumentByUUIDResponseMultiError, or nil if none found.
func (m *GetDocumentByUUIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDocumentByUUIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDocument()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetDocumentByUUIDResponseValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetDocumentByUUIDResponseValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDocument()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetDocumentByUUIDResponseValidationError{
				field:  "Document",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetDocumentByUUIDResponseMultiError(errors)
	}

	return nil
}

// GetDocumentByUUIDResponseMultiError is an error wrapping multiple validation
// errors returned by GetDocumentByUUIDResponse.ValidateAll() if the
// designated constraints aren't met.
type GetDocumentByUUIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDocumentByUUIDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDocumentByUUIDResponseMultiError) AllErrors() []error { return m }

// GetDocumentByUUIDResponseValidationError is the validation error returned by
// GetDocumentByUUIDResponse.Validate if the designated constraints aren't met.
type GetDocumentByUUIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDocumentByUUIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDocumentByUUIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDocumentByUUIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDocumentByUUIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDocumentByUUIDResponseValidationError) ErrorName() string {
	return "GetDocumentByUUIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetDocumentByUUIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDocumentByUUIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDocumentByUUIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDocumentByUUIDResponseValidationError{}

// Validate checks the field values on ReceiveDocumentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReceiveDocumentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReceiveDocumentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReceiveDocumentRequestMultiError, or nil if none found.
func (m *ReceiveDocumentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReceiveDocumentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ReceiveDocumentRequestMultiError(errors)
	}

	return nil
}

// ReceiveDocumentRequestMultiError is an error wrapping multiple validation
// errors returned by ReceiveDocumentRequest.ValidateAll() if the designated
// constraints aren't met.
type ReceiveDocumentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReceiveDocumentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReceiveDocumentRequestMultiError) AllErrors() []error { return m }

// ReceiveDocumentRequestValidationError is the validation error returned by
// ReceiveDocumentRequest.Validate if the designated constraints aren't met.
type ReceiveDocumentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReceiveDocumentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReceiveDocumentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReceiveDocumentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReceiveDocumentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReceiveDocumentRequestValidationError) ErrorName() string {
	return "ReceiveDocumentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReceiveDocumentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReceiveDocumentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReceiveDocumentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReceiveDocumentRequestValidationError{}

// Validate checks the field values on ReceiveDocumentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReceiveDocumentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReceiveDocumentResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReceiveDocumentResponseMultiError, or nil if none found.
func (m *ReceiveDocumentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReceiveDocumentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDocument()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReceiveDocumentResponseValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReceiveDocumentResponseValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDocument()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReceiveDocumentResponseValidationError{
				field:  "Document",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReceiveDocumentResponseMultiError(errors)
	}

	return nil
}

// ReceiveDocumentResponseMultiError is an error wrapping multiple validation
// errors returned by ReceiveDocumentResponse.ValidateAll() if the designated
// constraints aren't met.
type ReceiveDocumentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReceiveDocumentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReceiveDocumentResponseMultiError) AllErrors() []error { return m }

// ReceiveDocumentResponseValidationError is the validation error returned by
// ReceiveDocumentResponse.Validate if the designated constraints aren't met.
type ReceiveDocumentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReceiveDocumentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReceiveDocumentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReceiveDocumentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReceiveDocumentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReceiveDocumentResponseValidationError) ErrorName() string {
	return "ReceiveDocumentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReceiveDocumentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReceiveDocumentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReceiveDocumentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReceiveDocumentResponseValidationError{}
